version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.docker
    ports:
      - "80:7350"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    volumes:
      - ./assets:/var/spaceshipassets
      - .:/go/src/spaceship
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"